### ISSUE TITLE
Error in edit details function in a rack

### ISSUE THREAD

**Issue by anthonyhorlock** [AberystwythSystemsBiology/LImBuS#191] opened 2022-03-11 15:11 UTC
I clicked on the edit details function and got the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view    return func(*args, **kwargs)
  File "/limbus/app/storage/routes/rack.py", line 1147, in edit_rack    shelf_dict[int(shelf["site_id"])].append(KeyError: 3
'''

![image](https://user-images.githubusercontent.com/98022410/157894376-4359fdc5-18ed-4db7-ae3a-255c61b5fd63.png)

**Comment by KeironO** [comment] 2022-03-14 10:32
Duplicate of #192.

**Closed as completed by KeironO** 2022-03-14 10:32 UTC
